export const storeName = 'MAIN';

// Fetch data action types
export enum EUserActionsTypes {
  USER_LOAD_REQUEST = 'MAIN/USER_LOAD_REQUEST',
  USER_LOAD_SUCCESS = 'MAIN/USER_LOAD_SUCCESS',
  USER_LOAD_FAILURE = 'MAIN/USER_LOAD_FAILURE',
}

// Change settings action types
export enum ESettingsActionsTypes {
  // Visual settings
  SETTINGS_CHANGE_COLOR = 'SETTINGS/CHANGE_COLOR',
  SETTINGS_CHANGE_BACKGROUND = 'SETTINGS/CHANGE_BACKGROUND',

  // Enable/disable components
  SETTINGS_SHOW_TITLE = 'SETTINGS/CHANGE_SHOW_TITLE',
  SETTINGS_SHOW_TEXT = 'SETTINGS/CHANGE_SHOW_TEXT',
  SETTINGS_SHOW_SUBTITLE = 'SETTINGS/CHANGE_SHOW_SUBTITLE',
  SETTINGS_SHOW_FOOTER = 'SETTINGS/CHANGE_SHOW_FOOTER',
  SETTINGS_SHOW_RECENT = 'SETTINGS/CHANGE_SHOW_RECENT',

  // Change component text
  SETTINGS_CHANGE_TITLE = 'SETTINGS/CHANGE_TITLE',
  SETTINGS_CHANGE_TEXT = 'SETTINGS/CHANGE_TEXT',
  SETTINGS_CHANGE_SUBTITLE = 'SETTINGS/CHANGE_SUBTITLE',
}
